version: "3.7"

services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/local/structurizr

  structurizr-cli:
    image: structurizr/cli
    volumes:
      - ./:/usr/local/structurizr
    command: "push -id ${workspaceId} -key ${apiKey} -secret ${apiSecret} -w workspace.json"

  structurizr-export:
    image: structurizr/cli
    volumes:
      - ./:/usr/local/structurizr
    command: "export -workspace workspace.json -format plantuml"

  structurizr-genrate:
    image: ghcr.io/avisi-cloud/structurizr-site-generatr
    volumes:
      - ./:/var/model
    command: "generate-site -w workspace.dsl"


