@startuml
set separator none
title REST API - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

System(AdminPanel, "Admin Panel", "Administration and course authoring panel", $tags="")
System(WebApp, "Web App", "Wellms Front Course Access App", $tags="")
System(RESTAPI, "REST API", "", $tags="")

Rel_D(AdminPanel, RESTAPI, "Communicates", $tags="")
Rel_D(WebApp, RESTAPI, "Communicates", $tags="")

SHOW_LEGEND(true)
@enduml