@startuml
set separator none
title Admin Panel - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
System(AdminPanel, "Admin Panel", "Administration and course authoring panel", $tags="")[[../container/]]
System(SDK, "SDK", "Wellms Software Development Kit", $tags="")[[../../sdk/context/]]
Person(TutorContentAuthor, "Tutor/Content Author", "A content creator and e-learnig tutor.", $tags="")
Person(Admin, "Admin", "Administrator of the systems.", $tags="")
System(RESTAPI, "REST API", "", $tags="")[[../../rest-api/context/]]

Rel_D(Admin, AdminPanel, "Administer", $tags="")
Rel_D(TutorContentAuthor, AdminPanel, "Manage courses", $tags="")
Rel_D(AdminPanel, RESTAPI, "Communicates", $tags="")
Rel_D(AdminPanel, SDK, "package json dependecy", $tags="")

SHOW_LEGEND(true)
@enduml