@startuml
set separator none
title Admin Panel - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
System(SDK, "SDK", "Wellms Software Development Kit", $tags="")[[../../sdk/context/]]

System_Boundary("AdminPanel_boundary", "Admin Panel", $tags="") {
  Container(AdminPanel.AdminWebApp, "Admin Web App", "React Admin Panel", $tags="")[[../component/]]
}

Rel_D(AdminPanel.AdminWebApp, SDK, "package json dependecy", $tags="")

SHOW_LEGEND(true)
@enduml