@startuml
set separator none
title REST API - API Application - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Container(RESTAPI.ffmpeg, "ffmpeg", "video transcoder", "Video transcoder", $tags="")
Container(RESTAPI.Storage, "Storage", "Either/both extental (like s3) and internal (local)", "storage for files", $tags="")
Container(RESTAPI.Imageprocessingoptimizers, "Image processing optimizers", "JpegOptim, Optipng, Pngquant 2, SVGO 1, Gifsicle, cwebp", $tags="")
Container(RESTAPI.YoutubeAPI, "Youtube API", "youtube API", $tags="")

Container_Boundary("RESTAPI.APIApplication_boundary", "API Application", $tags="") {
  Component(RESTAPI.APIApplication.Core, "Core", "Core", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Auth, "Auth", "Auth. User authentication. Roles & Permission Management", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Assignwithoutaccount, "Assign-without-account", "Package enabling accessing courses and products without having account.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Cart, "Cart", "Cart. General shop management.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Categories, "Categories", "Categories", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Consultations, "Consultations", "Consultations. One to one conversation package with `jitsi`", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Courses, "Courses", "Courses. and content package", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Coursesimportexport, "Courses-import-export", "Courses Import Export. ZIP package and duplicate feature.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Csvusers, "Csv-users", "CSV-Users. Exporting and importing users in `.csv` format", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Fakturownia, "Fakturownia", "Fakturownia-Integration. Generates Invoice from Fakturowania", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Files, "Files", "Files. Uploading, deleting and reusing files.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.H5p, "H5p", "H5P Headless.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Images, "Images", "Images. Responsive and compressions processing module", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Invoices, "Invoices", "Invoices generation.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Jitsi, "Jitsi", "Jitsi.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Lrs, "Lrs", "LRS xAPI Learning Record Stores", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Mailerlite, "Mailerlite", "MailerLite. Customized group for LMS events", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Mattermost, "Mattermost", "Mattermost.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Modelfields, "Model-fields", "Model Fields. Extra attributes to any model", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Notifications, "Notifications", "Notifications.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Pages, "Pages", "Pages. Simple CMS.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Payments, "Payments", "Payments. Facades that allows to connect payment gateways", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Permissions, "Permissions", "Permissions and Roles.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Questionnaire, "Questionnaire", "Questionnaire. Answers & Reports", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Reports, "Reports", "Reports. Courses reports.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Scorm, "Scorm", "Scorm. Attach Scorm packages to courses", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Settings, "Settings", "Settings. Additional global fields of various types and other package setup", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Stationaryevents, "Stationary-events", "Stationary Events.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Tags, "Tags", "Tags. Tagging for any Module", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Templates, "Templates", "Templates.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Templatescertificates, "Templates-certificates", "Templates-Certificates. Editing certificate templates", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Templatesemail, "Templates-email", "Templates-Email. Notification management with custom mjml templates.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Templatespdf, "Templates-pdf", "Templates-PDF. Templates in fabric.js frontend rendering format.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Templatessms, "Templates-sms", "Templates-SMS. Notification management with custom templates", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Topictypes, "Topic-types", "Topic Types. List of possible Topic Types for Course content", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Tracker, "Tracker", "Tracker.", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Translations, "Translations", "Translations. (not implemented)", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Video, "Video", "Video Processing. Generation `hls` streaming formats", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Vouchers, "Vouchers", "Vouchers. E-commerce vouchers to manage cart promotion", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Webinar, "Webinar", "Webinar. Live video stream with `Jitsi` and `YouTube`", "Laravel Package", $tags="")
  Component(RESTAPI.APIApplication.Youtube, "Youtube", "Youtube. Package Youtube integration", "Laravel Package", $tags="")
}

Rel_D(RESTAPI.APIApplication.Payments, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Permissions, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Questionnaire, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Reports, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Scorm, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Settings, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Stationaryevents, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Tags, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Templates, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Templatescertificates, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Templatesemail, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Templatespdf, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Templatessms, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Topictypes, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Tracker, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Translations, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Video, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Vouchers, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Webinar, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Youtube, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Images, RESTAPI.Imageprocessingoptimizers, "use binary tools for image formating, resize and compression", $tags="")
Rel_D(RESTAPI.APIApplication.Images, RESTAPI.Storage, "saves processed images", $tags="")
Rel_D(RESTAPI.Imageprocessingoptimizers, RESTAPI.Storage, "saves processed images", $tags="")
Rel_D(RESTAPI.APIApplication.Video, RESTAPI.ffmpeg, "use binary tools for video transcoding, resize and compression", $tags="")
Rel_D(RESTAPI.APIApplication.Webinar, RESTAPI.YoutubeAPI, "publish on youtube", $tags="")
Rel_D(RESTAPI.APIApplication.Webinar, RESTAPI.APIApplication.Jitsi, "generate rooms thought API", $tags="")
Rel_D(RESTAPI.APIApplication.Consultations, RESTAPI.APIApplication.Jitsi, "generate one-to-one jitsi URLs", $tags="")
Rel_D(RESTAPI.APIApplication.Vouchers, RESTAPI.APIApplication.Cart, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Payments, RESTAPI.APIApplication.Cart, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Assignwithoutaccount, RESTAPI.APIApplication.Cart, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Coursesimportexport, RESTAPI.APIApplication.Courses, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Topictypes, RESTAPI.APIApplication.Courses, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Questionnaire, RESTAPI.APIApplication.Courses, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Video, RESTAPI.APIApplication.Topictypes, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Scorm, RESTAPI.APIApplication.Topictypes, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Assignwithoutaccount, RESTAPI.APIApplication.Courses, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Reports, RESTAPI.APIApplication.Courses, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Reports, RESTAPI.APIApplication.Cart, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Permissions, RESTAPI.APIApplication.Auth, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Csvusers, RESTAPI.APIApplication.Auth, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Jitsi, RESTAPI.APIApplication.Webinar, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Templatescertificates, RESTAPI.APIApplication.Templates, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Templatesemail, RESTAPI.APIApplication.Templates, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Templatespdf, RESTAPI.APIApplication.Templates, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Templatessms, RESTAPI.APIApplication.Templates, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Mailerlite, RESTAPI.APIApplication.Templatesemail, "relates on", $tags="")
Rel_D(RESTAPI.APIApplication.Auth, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Assignwithoutaccount, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Cart, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Categories, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Consultations, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Courses, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Coursesimportexport, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Csvusers, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Fakturownia, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Files, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.H5p, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Images, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Invoices, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Jitsi, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Lrs, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Mailerlite, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Mattermost, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Modelfields, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Notifications, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")
Rel_D(RESTAPI.APIApplication.Pages, RESTAPI.APIApplication.Core, "Core Dependecy", $tags="")

SHOW_LEGEND(true)
@enduml