name: Publish models

on:
  push:
    branches:
      - main

jobs:
  c4-publish:
    runs-on: ubuntu-latest

    env:
      workspaceId: 75191
      apiKey: ${{ secrets.apiKey }}
      apiSecret: ${{ secrets.apiSecret }}

    container:
      image: structurizr/cli

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Publish to cloud
        run: java -cp /usr/local/structurizr-cli:/usr/local/structurizr-cli/lib/* com.structurizr.cli.StructurizrCliApplication push -id ${workspaceId} -key ${apiKey} -secret ${apiSecret} -w workspace.json
